# S7 — Pandas Fundamentals

Practical notes and 26 solved exercises.

`DataFrame` · selection · filtering · sorting · CSV types · `groupby`

## 1. Setup

- `DataFrame`: two-dimensional table
- `Series`: one-dimensional labeled column

In [1]:
import pandas as pd

employees = pd.DataFrame({
    "name": ["Ada", "Bora", "Cem", "Deniz", "Ece", "Fırat"],
    "department": ["ML", "Backend", "ML", "Backend", "Data", "Data"],
    "age": [24, 27, 22, 29, 25, 31],
    "salary": [72000, 85000, 68000, 92000, 79000, 98000],
    "active": [True, True, False, True, True, False]
})

employees

    name department  age  salary  active
0    Ada         ML   24   72000    True
1   Bora    Backend   27   85000    True
2    Cem         ML   22   68000   False
3  Deniz    Backend   29   92000    True
4    Ece       Data   25   79000    True
5  Fırat       Data   31   98000   False

### Quick inspection

```python
df.head()
df.shape
df.columns
df.dtypes
df.info()
df.describe()
```

Useful extras:

```python
df.describe(include="all")
df["column"].value_counts(dropna=False)
```

In [2]:
employees.head()

    name department  age  salary  active
0    Ada         ML   24   72000    True
1   Bora    Backend   27   85000    True
2    Cem         ML   22   68000   False
3  Deniz    Backend   29   92000    True
4    Ece       Data   25   79000    True

In [3]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        6 non-null      object
 1   department  6 non-null      object
 2   age         6 non-null      int64
 3   salary      6 non-null      int64
 4   active      6 non-null      bool
dtypes: bool(1), int64(2), object(2)
memory usage: 330.0+ bytes

In [4]:
employees.describe()

             age        salary
count   6.000000      6.000000
mean   26.333333  82333.333333
std     3.326660  11570.076347
min    22.000000  68000.000000
25%    24.250000  73750.000000
50%    26.000000  82000.000000
75%    28.500000  90250.000000
max    31.000000  98000.000000

## 2. Selection: `.loc` and `.iloc`

```python
df["column"]          # Series
df[["column"]]        # DataFrame

df.loc[rows, columns]   # labels
df.iloc[rows, columns]  # integer positions
```

**Trick:** `.loc[1:3]` includes `3`; `.iloc[1:3]` does not.

### Exercise 1 — ★☆☆
Find the number of rows and columns in `employees`.

In [5]:
employees.shape

(6, 5)

### Exercise 2 — ★☆☆
Display the data type of every column.

In [6]:
employees.dtypes

name          object
department    object
age            int64
salary         int64
active          bool
dtype: object

### Exercise 3 — ★☆☆
Select only the `name` and `department` columns.

In [7]:
employees[["name", "department"]]

    name department
0    Ada         ML
1   Bora    Backend
2    Cem         ML
3  Deniz    Backend
4    Ece       Data
5  Fırat       Data

### Exercise 4 — ★☆☆
Using `.loc`, select rows with index labels `1`, `2`, and `3`, keeping only `name` and `salary`.

In [8]:
employees.loc[1:3, ["name", "salary"]]

    name  salary
1   Bora   85000
2    Cem   68000
3  Deniz   92000

### Exercise 5 — ★☆☆
Using `.iloc`, select the first three rows and the first two columns.

In [9]:
employees.iloc[0:3, 0:2]

   name department
0   Ada         ML
1  Bora    Backend
2   Cem         ML

### Exercise 6 — ★☆☆
Count how many employees belong to each department.

In [10]:
employees[["department"]].value_counts()

department
Backend       2
Data          2
ML            2
Name: count, dtype: int64

> `employees["department"].value_counts()` is the direct single-column version.

### Exercise 7 — ★★☆
Set `name` as the index and select Deniz's salary with `.loc`.

In [11]:
employees.set_index("name").loc["Deniz", "salary"]

np.int64(92000)

## 3. Boolean Indexing and `.query()`

```python
df[condition]
df.loc[condition, ["col1", "col2"]]
```

```python
(cond1) & (cond2)   # and
(cond1) | (cond2)   # or
~condition          # not
```

Useful patterns:

```python
df["column"].isin(["A", "B"])
df.query("salary >= 80000 and active")
df.query("salary >= @minimum_salary")
```

**Trick:** use `&` / `|`, not Python's `and` / `or`.

### Exercise 8 — ★☆☆
Select employees whose salary is at least `80000`.

In [12]:
employees[employees["salary"] >= 80000]

    name department  age  salary  active
1   Bora    Backend   27   85000    True
3  Deniz    Backend   29   92000    True
5  Fırat       Data   31   98000   False

### Exercise 9 — ★☆☆
Select inactive employees.

In [13]:
employees[employees["active"] == False]

    name department  age  salary  active
2    Cem         ML   22   68000   False
5  Fırat       Data   31   98000   False

### Exercise 10 — ★☆☆
Using `.loc`, select only the `name` and `salary` columns for employees in the ML department.

In [14]:
employees.loc[employees["department"] == "ML", ["name", "salary"]]

  name  salary
0  Ada   72000
2  Cem   68000

### Exercise 11 — ★☆☆
Select employees who are active and at least 25 years old.

In [15]:
employees[(employees["active"] == True) & (employees["age"] >= 25)]

    name department  age  salary  active
1   Bora    Backend   27   85000    True
3  Deniz    Backend   29   92000    True
4    Ece       Data   25   79000    True

### Exercise 12 — ★★☆
Select employees in either ML or Data. Solve it once with `|` and once with `.isin()`.

In [16]:
employees[(employees["department"] == "ML") | (employees["department"] == "Data")]

    name department  age  salary  active
0    Ada         ML   24   72000    True
2    Cem         ML   22   68000   False
4    Ece       Data   25   79000    True
5  Fırat       Data   31   98000   False

In [17]:
employees[employees["department"].isin(["ML", "Data"])]

    name department  age  salary  active
0    Ada         ML   24   72000    True
2    Cem         ML   22   68000   False
4    Ece       Data   25   79000    True
5  Fırat       Data   31   98000   False

### Exercise 13 — ★★☆
Select active employees younger than 30 whose salary is at least `75000`. Solve it with Boolean indexing and `.query()`.

In [18]:
employees[(employees["active"] == True) & (employees["age"] < 30) & (employees["salary"] >= 75000)]

    name department  age  salary  active
1   Bora    Backend   27   85000    True
3  Deniz    Backend   29   92000    True
4    Ece       Data   25   79000    True

In [19]:
employees.query("salary >= 75000 and age < 30 and active == True")

    name department  age  salary  active
1   Bora    Backend   27   85000    True
3  Deniz    Backend   29   92000    True
4    Ece       Data   25   79000    True

### Exercise 14 — ★★☆
Use an external variable named `minimum_salary` inside `.query()` to select salaries of at least `85000`.

In [20]:
minimum_salary = 85000
employees.query("salary >= @minimum_salary")

    name department  age  salary  active
1   Bora    Backend   27   85000    True
3  Deniz    Backend   29   92000    True
5  Fırat       Data   31   98000   False

## 4. Sorting

```python
df.sort_values("column")
df.sort_values("column", ascending=False)

df.sort_values(
    ["department", "salary"],
    ascending=[True, False]
)
```

Use `ignore_index=True` when you want a fresh `0..n-1` index.

### Exercise 15 — ★☆☆
Sort employees by salary from highest to lowest.

In [21]:
employees.sort_values("salary", ascending=False)

    name department  age  salary  active
5  Fırat       Data   31   98000   False
3  Deniz    Backend   29   92000    True
1   Bora    Backend   27   85000    True
4    Ece       Data   25   79000    True
0    Ada         ML   24   72000    True
2    Cem         ML   22   68000   False

### Exercise 16 — ★☆☆
Sort employees by age from youngest to oldest and reset the resulting index.

In [22]:
employees.sort_values("age", ascending=True, ignore_index=True)

    name department  age  salary  active
0    Cem         ML   22   68000   False
1    Ada         ML   24   72000    True
2    Ece       Data   25   79000    True
3   Bora    Backend   27   85000    True
4  Deniz    Backend   29   92000    True
5  Fırat       Data   31   98000   False

### Exercise 17 — ★★☆
Sort by department alphabetically, then by salary from highest to lowest within each department.

In [23]:
employees.sort_values(by=["department", "salary"], ascending=[True, False])

    name department  age  salary  active
3  Deniz    Backend   29   92000    True
1   Bora    Backend   27   85000    True
5  Fırat       Data   31   98000   False
4    Ece       Data   25   79000    True
0    Ada         ML   24   72000    True
2    Cem         ML   22   68000   False

## 5. Reading CSV Files

```python
pd.read_csv(
    path_or_buffer,
    dtype={
        "employee_id": "string",
        "department": "category"
    },
    parse_dates=["start_date"]
)
```

**Tricks**

- IDs such as `001` should usually be strings.
- Parse dates while loading when possible.
- Check the result immediately with `.dtypes`.
- Reusing a `StringIO` object: call `csv_data.seek(0)` first.

In [24]:
from io import StringIO

csv_data = StringIO("""
employee_id,name,department,salary,start_date,active
001,Ada,ML,72000,2025-09-15,True
002,Bora,Backend,85000,2024-03-10,True
003,Cem,ML,68000,2026-01-20,False
004,Deniz,Backend,92000,2023-11-05,True
005,Ece,Data,79000,2025-06-12,True
006,Fırat,Data,98000,2022-08-25,False
""".strip())

### Exercise 18 — ★☆☆
Read the CSV without `dtype` or `parse_dates`, then inspect both the table and inferred data types.

In [25]:
csv_data.seek(0)
raw_employees = pd.read_csv(csv_data)
raw_employees

   employee_id   name department  salary  start_date  active
0            1    Ada         ML   72000  2025-09-15    True
1            2   Bora    Backend   85000  2024-03-10    True
2            3    Cem         ML   68000  2026-01-20   False
3            4  Deniz    Backend   92000  2023-11-05    True
4            5    Ece       Data   79000  2025-06-12    True
5            6  Fırat       Data   98000  2022-08-25   False

In [26]:
raw_employees.dtypes

employee_id     int64
name           object
department     object
salary          int64
start_date     object
active           bool
dtype: object

> Without an explicit `dtype`, `001` becomes `1`. Without `parse_dates`, `start_date` stays string-like.

### Exercise 19 — ★★☆
Read the same CSV using the following types: `employee_id → string`, `department → category`, `salary → int64`, `active → bool`, and parse `start_date` as a date.

In [27]:
csv_data.seek(0)

employees_csv = pd.read_csv(
    csv_data,
    dtype={
        "employee_id": "string",
        "department": "category",
        "salary": "int64",
        "active": "bool"
    },
    parse_dates=["start_date"]
)

employees_csv.dtypes

employee_id    string[python]
name                   object
department           category
salary                  int64
start_date     datetime64[ns]
active                   bool
dtype: object

Datetime columns support the `.dt` accessor:

```python
df["start_date"].dt.year
df["start_date"].dt.month
```

In [28]:
employees_csv["start_date"].dt.year

0    2025
1    2024
2    2026
3    2023
4    2025
5    2022
Name: start_date, dtype: int32

In [29]:
employees_csv["start_date"].dt.month

0     9
1     3
2     1
3    11
4     6
5     8
Name: start_date, dtype: int32

### Exercise 20 — ★★☆
Select active employees who started on or after `2025-01-01`, then sort them from the earliest to the latest start date.

In [30]:
employees_csv[
    (employees_csv["start_date"] >= "2025-01-01")
    & (employees_csv["active"] == True)
].sort_values("start_date")

  employee_id name department  salary start_date  active
4         005  Ece       Data   79000 2025-06-12    True
0         001  Ada         ML   72000 2025-09-15    True

## 6. Grouping and Aggregation

Basic pattern:

```python
df.groupby("department")["salary"].mean()
```

Multiple functions:

```python
df.groupby("department").agg({
    "salary": ["mean", "std", "count"],
    "age": ["min", "max"]
})
```

Named aggregation:

```python
df.groupby("department", as_index=False).agg(
    average_salary=("salary", "mean"),
    employee_count=("name", "count")
)
```

**Tricks**

- `size()` counts rows.
- `count()` ignores missing values.
- Dictionary-based `.agg()` may create MultiIndex columns.
- Named aggregation gives clean output column names.

### Exercise 21 — ★☆☆
Calculate the average salary for each department.

In [31]:
employees.groupby("department", as_index=True).agg({"salary": ["mean"]})

             salary
               mean
department
Backend     88500.0
Data        88500.0
ML          70000.0

### Exercise 22 — ★☆☆
Count employees in each department using `groupby().size()`.

In [32]:
employees.groupby("department", as_index=True).size()

department
Backend    2
Data       2
ML         2
dtype: int64

### Exercise 23 — ★★☆
For each department, calculate `mean`, `std`, and `count` for the `salary` column using dictionary-based `.agg()`.

In [33]:
employees.groupby("department", as_index=True).agg({"salary": ["mean", "std", "count"]})

             salary
               mean           std count
department
Backend     88500.0   4949.747468     2
Data        88500.0  13435.028843     2
ML          70000.0   2828.427125     2

### Exercise 24 — ★★☆
For each department, calculate `mean`, `min`, and `max` for both `salary` and `age`.

In [34]:
employees.groupby("department", as_index=True).agg({"salary": ["mean", "min", "max"], "age": ["mean", "min", "max"]})

             salary                 age
               mean    min    max  mean min max
department
Backend     88500.0  85000  92000  28.0  27  29
Data        88500.0  79000  98000  28.0  25  31
ML          70000.0  68000  72000  23.0  22  24

### Exercise 25 — ★★☆
Using named aggregation, create a result with `department`, `average_salary`, `highest_salary`, `employee_count`, and `average_age`. Keep `department` as a normal column.

In [35]:
employees.groupby("department", as_index=False).agg(
    average_salary=("salary", "mean"),
    highest_salary=("salary", "max"),
    employee_count=("name", "count"),
    average_age=("age", "mean")
)

  department  average_salary  highest_salary  employee_count  average_age
0    Backend         88500.0           92000               2         28.0
1       Data         88500.0           98000               2         28.0
2         ML         70000.0           72000               2         23.0

### Exercise 26 — ★★☆
Filter active employees, group them by department, and produce `active_employee_count` and `average_active_salary`.

In [36]:
employees[employees["active"] == True].groupby(
    "department",
    as_index=False
).agg(
    active_employee_count=("name", "count"),
    average_active_salary=("salary", "mean")
)

  department  active_employee_count  average_active_salary
0    Backend                      2                88500.0
1       Data                      1                79000.0
2         ML                      1                72000.0

## Quick Reference

```python
# inspect
df.head()
df.info()
df.describe()

# select
df.loc[condition, ["col1", "col2"]]
df.iloc[:5, :3]

# filter
df[df["x"].isin(values)]
df.query("x >= @limit")

# sort
df.sort_values("x", ascending=False)

# group
df.groupby("group", as_index=False).agg(
    average=("value", "mean"),
    count=("value", "count")
)
```

Next: selected problems from `100-pandas-puzzles`.